package lk.dmc.disaster.analytics.export;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.StringReader;
import java.util.List;
import java.util.Map;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVRecord;
import org.junit.jupiter.api.Test;

class CsvReportExporterTest {

  private final CsvReportExporter exporter = new CsvReportExporter();

  private List<CSVRecord> export(DisasterReportView view) throws IOException {
    String csv = new String(exporter.export(view), java.nio.charset.StandardCharsets.UTF_8);
    return CSVFormat.DEFAULT.builder().setHeader().setSkipHeaderRecord(true).get()
        .parse(new StringReader(csv))
        .getRecords();
  }

  /** The record of this section and label, failing the test when it is missing. */
  private static CSVRecord row(List<CSVRecord> rows, String section, String label) {
    return rows.stream()
        .filter(r -> r.get("section").equals(section) && r.get("label").equals(label))
        .findFirst()
        .orElseThrow(() -> new AssertionError("no row " + section + " / " + label + " in " + rows));
  }

  @Test
  void format_isCsv() {
    assertThat(exporter.format()).isEqualTo(ExportFormat.CSV);
  }

  @Test
  void export_headerIsSectionLabelValueExtra() throws IOException {
    String csv = new String(exporter.export(ReportViews.of(Map.of(), List.of())));

    assertThat(csv).startsWith("section,label,value,extra");
  }

  @Test
  void export_startsWithTheReportSummary() throws IOException {
    var rows = export(ReportViews.of(Map.of(), List.of()));

    assertThat(row(rows, "REPORT", "Event").get("value")).isEqualTo("Kalu Flood May 2026");
    assertThat(row(rows, "REPORT", "Generated by").get("value")).isEqualTo("Nimal Perera");
    assertThat(row(rows, "REPORT", "Generated at").get("value")).isEqualTo("2026-10-04T08:00:00Z");
    assertThat(row(rows, "REPORT", "Districts").get("value")).isEqualTo("2");
    assertThat(row(rows, "REPORT", "From").get("value")).isEqualTo("2026-05-14T00:10:00Z");
    assertThat(row(rows, "REPORT", "To").get("value")).isEqualTo("2026-05-16T00:00:00Z");
  }

  @Test
  void export_alertTimeline_hasTimesAndOneRowPerWarning() throws IOException {
    var rows = export(ReportViews.of(ReportViews.allSections(), List.of()));

    assertThat(row(rows, "ALERT_TIMELINE", "First warning").get("value")).isEqualTo("2026-05-14T01:30:00Z");
    assertThat(row(rows, "ALERT_TIMELINE", "First verified report").get("value")).isEqualTo("2026-05-14T00:05:00Z");
    assertThat(row(rows, "ALERT_TIMELINE", "Minutes from report to warning").get("value")).isEqualTo("85");
    assertThat(row(rows, "ALERT_TIMELINE", "WATCH ESCALATED").get("value")).isEqualTo("2026-05-14T01:30:00Z");
    assertThat(row(rows, "ALERT_TIMELINE", "WARNING ESCALATED").get("extra")).contains("supersedes w1");
  }

  @Test
  void export_citizensReached_hasTheTotalsChannelsAndDistricts() throws IOException {
    var rows = export(ReportViews.of(ReportViews.allSections(), List.of()));

    assertThat(row(rows, "CITIZENS_REACHED", "Citizens targeted").get("value")).isEqualTo("17");
    assertThat(row(rows, "CITIZENS_REACHED", "Citizens reached").get("value")).isEqualTo("17");
    assertThat(row(rows, "CITIZENS_REACHED", "Delivery rate").get("value")).isEqualTo("1.0");
    var sms = row(rows, "CITIZENS_REACHED", "Channel SMS");
    assertThat(sms.get("value")).isEqualTo("47");
    assertThat(sms.get("extra")).isEqualTo("failed=4");
    assertThat(row(rows, "CITIZENS_REACHED", "Ratnapura").get("extra")).isEqualTo("targeted=8");
  }

  @Test
  void export_shelterOccupancy_hasPointsAndPeaksAndKeepsCommasInNames() throws IOException {
    var rows = export(ReportViews.of(ReportViews.allSections(), List.of()));

    var peak = row(rows, "SHELTER_OCCUPANCY", "Peak Sivali, Central College");
    assertThat(peak.get("value")).isEqualTo("290");
    assertThat(peak.get("extra")).contains("capacity=300", "ratio=0.97", "at=2026-05-16T04:00:00Z");
    assertThat(row(rows, "SHELTER_OCCUPANCY", "Sivali, Central College 2026-05-14T22:00:00Z").get("value"))
        .isEqualTo("20");
  }

  @Test
  void export_resourceDistribution_hasDistrictItemOwnerAndItemRows() throws IOException {
    var rows = export(ReportViews.of(ReportViews.allSections(), List.of()));

    var district = row(rows, "RESOURCE_DISTRIBUTION", "Ratnapura DRY_RATION");
    assertThat(district.get("value")).isEqualTo("250");
    assertThat(district.get("extra")).isEqualTo("allocated=250 unit=packs");
    assertThat(row(rows, "RESOURCE_DISTRIBUTION", "Owner GOVERNMENT").get("value")).isEqualTo("250");
    assertThat(row(rows, "RESOURCE_DISTRIBUTION", "Item DRY_RATION").get("extra")).isEqualTo("unit=packs");
  }

  @Test
  void export_anUnavailableSectionGetsADataUnavailableRowWithItsReason() throws IOException {
    var rows =
        export(
            ReportViews.of(
                Map.of(),
                List.of(Map.of("key", "SHELTER_OCCUPANCY", "reason", "No shelter occupancy was logged for this event."))));

    var missing = row(rows, "SHELTER_OCCUPANCY", "Data unavailable");
    assertThat(missing.get("value")).isEmpty();
    assertThat(missing.get("extra")).isEqualTo("No shelter occupancy was logged for this event.");
  }

  @Test
  void export_aSectionWithoutDataWritesNoRows() throws IOException {
    var rows = export(ReportViews.of(Map.of("ALERT_TIMELINE", Map.of()), List.of()));

    assertThat(rows).noneMatch(r -> r.get("section").equals("ALERT_TIMELINE"));
  }

  @Test
  void export_missingValuesBecomeEmptyCellsNotTheWordNull() throws IOException {
    var sparse = Map.<String, Object>of("ALERT_TIMELINE", Map.of("entries", List.of(Map.of("level", "WATCH"))));
    var rows = export(ReportViews.of(sparse, List.of()));

    assertThat(row(rows, "ALERT_TIMELINE", "First warning").get("value")).isEmpty();
    assertThat(rows).noneMatch(r -> String.join(",", r.values()).contains("null"));
  }
}
