package lk.dmc.disaster.analytics.export;

import static lk.dmc.disaster.analytics.export.ExportValues.decimal;
import static lk.dmc.disaster.analytics.export.ExportValues.instant;
import static lk.dmc.disaster.analytics.export.ExportValues.list;
import static lk.dmc.disaster.analytics.export.ExportValues.map;
import static lk.dmc.disaster.analytics.export.ExportValues.number;
import static lk.dmc.disaster.analytics.export.ExportValues.text;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import lk.dmc.disaster.analytics.entity.AnalyticsRules;
import lk.dmc.disaster.analytics.entity.SectionKey;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.springframework.stereotype.Component;

/**
 * One CSV with the columns {@code section,label,value,extra}: a row per figure, so the file opens
 * in a spreadsheet without any reshaping. A section without data gets one "Data unavailable" row.
 */
@Component
public class CsvReportExporter implements ReportExporter {

  private static final CSVFormat FORMAT =
      CSVFormat.DEFAULT.builder().setHeader("section", "label", "value", "extra").get();

  /** The format this exporter writes: {@link ExportFormat#CSV}. */
  @Override
  public ExportFormat format() {
    return ExportFormat.CSV;
  }

  /** Writes the report as CSV with the columns {@code section,label,value,extra}. */
  @Override
  public byte[] export(DisasterReportView report) {
    try (ByteArrayOutputStream out = new ByteArrayOutputStream();
        OutputStreamWriter writer = new OutputStreamWriter(out, StandardCharsets.UTF_8);
        CSVPrinter csv = new CSVPrinter(writer, FORMAT)) {
      writeSummary(csv, report);
      Map<String, Object> sections = report.sections();
      writeAlertTimeline(csv, map(sections.get(SectionKey.ALERT_TIMELINE.name())));
      writeCitizensReached(csv, map(sections.get(SectionKey.CITIZENS_REACHED.name())));
      writeShelterOccupancy(csv, map(sections.get(SectionKey.SHELTER_OCCUPANCY.name())));
      writeResourceDistribution(csv, map(sections.get(SectionKey.RESOURCE_DISTRIBUTION.name())));
      for (Map<String, String> missing : report.unavailableSections()) {
        csv.printRecord(
            missing.get("key"), AnalyticsRules.DATA_UNAVAILABLE, "", missing.get("reason"));
      }
      csv.flush();
      return out.toByteArray();
    } catch (IOException e) {
      throw new UncheckedIOException("Could not write the CSV report.", e);
    }
  }

  private static void writeSummary(CSVPrinter csv, DisasterReportView report) throws IOException {
    csv.printRecord("REPORT", "Event", report.eventName(), "");
    csv.printRecord("REPORT", "Generated by", report.generatedByName(), "");
    csv.printRecord("REPORT", "Generated at", report.generatedAt(), "");
    Object districts = report.filters().get("districtIds");
    if (districts != null) {
      csv.printRecord("REPORT", "Districts", list(districts).size(), "");
    }
    csv.printRecord("REPORT", "From", text(report.filters().get("from")), "");
    csv.printRecord("REPORT", "To", text(report.filters().get("to")), "");
  }

  private static void writeAlertTimeline(CSVPrinter csv, Map<?, ?> section) throws IOException {
    if (section.isEmpty()) {
      return;
    }
    String key = SectionKey.ALERT_TIMELINE.name();
    csv.printRecord(key, "First warning", time(section.get("firstWarningAt")), "");
    csv.printRecord(key, "First verified report", time(section.get("firstVerifiedReportAt")), "");
    csv.printRecord(
        key, "Minutes from report to warning", text(section.get("reportToWarningMinutes")), "");
    for (Object entry : list(section.get("entries"))) {
      Map<?, ?> e = map(entry);
      String supersedes =
          e.get("supersedesId") == null ? "" : "supersedes " + text(e.get("supersedesId"));
      csv.printRecord(
          key,
          text(e.get("level")) + " " + text(e.get("status")),
          time(e.get("issuedAt")),
          ("warning " + text(e.get("warningId")) + " " + supersedes).trim());
    }
  }

  private static void writeCitizensReached(CSVPrinter csv, Map<?, ?> section) throws IOException {
    if (section.isEmpty()) {
      return;
    }
    String key = SectionKey.CITIZENS_REACHED.name();
    csv.printRecord(key, "Citizens targeted", number(section.get("uniqueCitizensTargeted")), "");
    csv.printRecord(key, "Citizens reached", number(section.get("uniqueCitizensReached")), "");
    csv.printRecord(key, "Delivery rate", decimal(section.get("deliveryRate")), "");
    for (Object channel : list(section.get("byChannel"))) {
      Map<?, ?> c = map(channel);
      csv.printRecord(
          key, "Channel " + text(c.get("channel")), number(c.get("delivered")),
          "failed=" + number(c.get("failed")));
    }
    for (Object district : list(section.get("byDistrict"))) {
      Map<?, ?> d = map(district);
      csv.printRecord(
          key, text(d.get("districtName")), number(d.get("reached")),
          "targeted=" + number(d.get("targeted")));
    }
  }

  private static void writeShelterOccupancy(CSVPrinter csv, Map<?, ?> section) throws IOException {
    if (section.isEmpty()) {
      return;
    }
    String key = SectionKey.SHELTER_OCCUPANCY.name();
    Map<String, String> names = new HashMap<>();
    for (Object series : list(section.get("series"))) {
      Map<?, ?> s = map(series);
      names.put(text(s.get("shelterId")), text(s.get("shelterName")));
      for (Object point : list(s.get("points"))) {
        Map<?, ?> p = map(point);
        csv.printRecord(
            key, text(s.get("shelterName")) + " " + time(p.get("recordedAt")),
            number(p.get("occupancy")), "capacity=" + number(s.get("capacity")));
      }
    }
    for (Object peak : list(section.get("peaks"))) {
      Map<?, ?> p = map(peak);
      csv.printRecord(
          key,
          "Peak " + names.getOrDefault(text(p.get("shelterId")), text(p.get("shelterId"))),
          number(p.get("peakOccupancy")),
          "capacity=" + number(p.get("capacity")) + " ratio=" + decimal(p.get("peakRatio"))
              + " at=" + time(p.get("peakAt")));
    }
  }

  private static void writeResourceDistribution(CSVPrinter csv, Map<?, ?> section)
      throws IOException {
    if (section.isEmpty()) {
      return;
    }
    String key = SectionKey.RESOURCE_DISTRIBUTION.name();
    for (Object row : list(section.get("byDistrict"))) {
      Map<?, ?> r = map(row);
      csv.printRecord(
          key, text(r.get("districtName")) + " " + text(r.get("itemCode")),
          number(r.get("distributed")),
          "allocated=" + number(r.get("allocated")) + " unit=" + text(r.get("unit")));
    }
    for (Object row : list(section.get("byOrganisationType"))) {
      Map<?, ?> r = map(row);
      csv.printRecord(key, "Owner " + text(r.get("type")), number(r.get("distributed")), "");
    }
    for (Object row : list(section.get("byItem"))) {
      Map<?, ?> r = map(row);
      csv.printRecord(
          key, "Item " + text(r.get("itemCode")), number(r.get("distributed")),
          "unit=" + text(r.get("unit")));
    }
  }

  private static String time(Object value) {
    return instant(value).map(Object::toString).orElse("");
  }
}
