package lk.dmc.disaster.analytics.export;

import java.io.ByteArrayOutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import lk.dmc.disaster.analytics.domain.DisasterReport;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.springframework.stereotype.Component;

@Component
public class CsvReportExporter implements ReportExporter {

    @Override
    public boolean supports(String format) {
        return "CSV".equals(format);
    }

    @Override
    public byte[] export(DisasterReport report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream();
             OutputStreamWriter writer = new OutputStreamWriter(out, StandardCharsets.UTF_8);
             CSVPrinter printer = new CSVPrinter(writer, CSVFormat.DEFAULT.builder().setHeader("Key", "Value").build())) {
             
            printer.printRecord("Event ID", report.getEventId());
            printer.printRecord("Generated By", report.getGeneratedBy());
            printer.printRecord("Generated At", report.getGeneratedAt());
            
            report.getSections().forEach((key, val) -> {
                try {
                    printer.printRecord(key, val.toString());
                } catch (Exception e) {}
            });
            
            printer.flush();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate CSV report", e);
        }
    }
}
