package lk.dmc.disaster.analytics.export;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import lk.dmc.disaster.analytics.domain.DisasterReport;
import org.springframework.stereotype.Component;

@Component
public class PdfReportExporter implements ReportExporter {

    @Override
    public boolean supports(String format) {
        return "PDF".equals(format);
    }

    @Override
    public byte[] export(DisasterReport report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, out);
            document.open();
            
            document.add(new Paragraph("Disaster Analytics Report"));
            document.add(new Paragraph("Event ID: " + report.getEventId()));
            document.add(new Paragraph("Generated By: " + report.getGeneratedBy()));
            document.add(new Paragraph("Generated At: " + report.getGeneratedAt()));
            
            document.add(new Paragraph("Sections:"));
            report.getSections().forEach((key, val) -> {
                try {
                    document.add(new Paragraph(key + ": " + val.toString()));
                } catch (Exception e) {}
            });
            
            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }
}
