package lk.dmc.disaster.analytics.export;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import lk.dmc.disaster.analytics.entity.AnalyticsRules;
import lk.dmc.disaster.analytics.entity.SectionKey;
import org.springframework.stereotype.Component;

/**
 * Renders a DisasterReport to a styled PDF using OpenPDF (LibrePDF fork of iText 2.x).
 *
 * Section keys stored in the DB are the enum constant names from SectionKey:
 *   ALERT_TIMELINE, CITIZENS_REACHED, SHELTER_OCCUPANCY, RESOURCE_DISTRIBUTION
 */
@Component
public class PdfReportExporter implements ReportExporter {

    // ── Fonts ──────────────────────────────────────────────────────────────
    private static final Font TITLE_FONT      = new Font(Font.HELVETICA, 18, Font.BOLD,   new Color(24, 54, 110));
    private static final Font HEADING_FONT    = new Font(Font.HELVETICA, 13, Font.BOLD,   new Color(24, 54, 110));
    private static final Font SUBHEAD_FONT    = new Font(Font.HELVETICA, 11, Font.BOLD,   new Color(50, 50, 70));
    private static final Font BODY_FONT       = new Font(Font.HELVETICA, 10, Font.NORMAL, new Color(50, 50, 70));
    private static final Font SMALL_FONT      = new Font(Font.HELVETICA,  9, Font.NORMAL, new Color(50, 50, 70));
    private static final Font TH_FONT         = new Font(Font.HELVETICA,  9, Font.BOLD,   Color.WHITE);
    private static final Color HEADER_BG      = new Color(24, 54, 110);
    private static final Color ROW_ODD_BG     = new Color(240, 244, 252);
    private static final Color ROW_EVEN_BG    = Color.WHITE;
    private static final Color BORDER_COLOR   = new Color(210, 215, 230);

    private static final DateTimeFormatter DT_FMT =
        DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm 'UTC'").withZone(ZoneId.of("UTC"));

    /** The format this exporter writes: {@link ExportFormat#PDF}. */
    @Override
    public ExportFormat format() { return ExportFormat.PDF; }

    // ── Main export ────────────────────────────────────────────────────────
    /** Writes the report as a styled PDF document. */
    @Override
    public byte[] export(DisasterReportView report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 56, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();

            writeHeader(doc, report);

            Map<String, Object> sections = report.sections();

            int n = 1;
            // 1. Alert Timeline
            Object tl = sections.get("ALERT_TIMELINE");
            if (tl instanceof Map<?, ?> m) {
                writeAlertTimeline(doc, m, n++);
            }

            // 2. Citizens Reached
            Object cr = sections.get("CITIZENS_REACHED");
            if (cr instanceof Map<?, ?> m) {
                writeCitizensReached(doc, m, n++);
            }

            // 3. Shelter Occupancy
            Object so = sections.get("SHELTER_OCCUPANCY");
            if (so instanceof Map<?, ?> m) {
                writeShelterOccupancy(doc, m, n++);
            }

            // 4. Resource Distribution
            Object rd = sections.get("RESOURCE_DISTRIBUTION");
            if (rd instanceof Map<?, ?> m) {
                writeResourceDistribution(doc, m, n++);
            }

            // Unavailable sections notice
            writeUnavailable(doc, report.unavailableSections());

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }

    // ── Section writers ────────────────────────────────────────────────────

    private void writeHeader(Document doc, DisasterReportView report) throws DocumentException {
        doc.add(new Paragraph("SafeLanka Disaster Analytics Report", TITLE_FONT));
        doc.add(spacer(4));
        doc.add(bodyLine("Event:         " + report.eventName()));
        doc.add(bodyLine("Generated At:  " + DT_FMT.format(report.generatedAt())));
        doc.add(bodyLine("Generated By:  " + report.generatedByName()));
        doc.add(spacer(14));
    }

    private void writeAlertTimeline(Document doc, Map<?, ?> tl, int num) throws DocumentException {
        doc.add(sectionHeading(num + ". Alert Timeline"));

        addKv(doc, "First Warning Issued",      fmtInstant(tl.get("firstWarningAt")));
        addKv(doc, "First Verified Report",     fmtInstant(tl.get("firstVerifiedReportAt")));
        addKv(doc, "Report-to-Warning (mins)",  tl.get("reportToWarningMinutes"));
        doc.add(spacer(6));

        List<?> entries = asList(tl.get("entries"));
        if (entries != null && !entries.isEmpty()) {
            doc.add(new Paragraph("Warning entries", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{32f, 14f, 16f, 38f});
            addTH(t, "Warning ID", "Level", "Status", "Issued At");
            int row = 0;
            for (Object entry : entries) {
                if (entry instanceof Map<?, ?> e) {
                    addTD(t, row++,
                        str(e.get("warningId")),
                        str(e.get("level")),
                        str(e.get("status")),
                        fmtInstant(e.get("issuedAt")));
                }
            }
            doc.add(t);
        }
        doc.add(spacer(12));
    }

    private void writeCitizensReached(Document doc, Map<?, ?> cr, int num) throws DocumentException {
        doc.add(sectionHeading(num + ". Citizens Reached"));

        long targeted = toLong(cr.get("uniqueCitizensTargeted"));
        long reached  = toLong(cr.get("uniqueCitizensReached"));
        Object rate   = cr.get("deliveryRate");
        addKv(doc, "Unique Citizens Targeted", targeted);
        addKv(doc, "Unique Citizens Reached",  reached);
        if (rate != null) {
            double pct = toDouble(rate) * 100.0;
            addKv(doc, "Delivery Rate", String.format("%.1f%%", pct));
        }
        doc.add(spacer(6));

        List<?> byChannel = asList(cr.get("byChannel"));
        if (byChannel != null && !byChannel.isEmpty()) {
            doc.add(new Paragraph("By notification channel", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{45f, 27f, 28f});
            addTH(t, "Channel", "Delivered", "Failed");
            int row = 0;
            for (Object ch : byChannel) {
                if (ch instanceof Map<?, ?> c) {
                    addTD(t, row++, str(c.get("channel")), str(c.get("delivered")), str(c.get("failed")));
                }
            }
            doc.add(t);
        }

        List<?> byDistrict = asList(cr.get("byDistrict"));
        if (byDistrict != null && !byDistrict.isEmpty()) {
            doc.add(spacer(6));
            doc.add(new Paragraph("By district", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{45f, 27f, 28f});
            addTH(t, "District", "Targeted", "Reached");
            int row = 0;
            for (Object d : byDistrict) {
                if (d instanceof Map<?, ?> dm) {
                    addTD(t, row++, str(dm.get("districtName")), str(dm.get("targeted")), str(dm.get("reached")));
                }
            }
            doc.add(t);
        }
        doc.add(spacer(12));
    }

    private void writeShelterOccupancy(Document doc, Map<?, ?> so, int num) throws DocumentException {
        doc.add(sectionHeading(num + ". Shelter Occupancy"));

        List<?> peaks = asList(so.get("peaks"));
        if (peaks != null && !peaks.isEmpty()) {
            doc.add(new Paragraph("Peak occupancy per shelter", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{37f, 18f, 18f, 27f});
            addTH(t, "Shelter ID", "Peak Occupancy", "Capacity", "Peak At");
            int row = 0;
            for (Object p : peaks) {
                if (p instanceof Map<?, ?> pm) {
                    int peak = (int) toLong(pm.get("peakOccupancy"));
                    int cap  = (int) toLong(pm.get("capacity"));
                    String ratio = cap > 0 ? String.format("%.0f%% full", 100.0 * peak / cap) : "?";
                    addTD(t, row++,
                        str(pm.get("shelterId")),
                        peak + "  (" + ratio + ")",
                        str(pm.get("capacity")),
                        fmtInstant(pm.get("peakAt")));
                }
            }
            doc.add(t);
        }

        List<?> series = asList(so.get("series"));
        if (series != null && !series.isEmpty()) {
            doc.add(spacer(6));
            doc.add(new Paragraph("Occupancy over time (per shelter)", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{30f, 20f, 50f});
            addTH(t, "Shelter", "Capacity", "Points (time → occupancy)");
            int row = 0;
            for (Object s : series) {
                if (s instanceof Map<?, ?> sm) {
                    List<?> pts = asList(sm.get("points"));
                    StringBuilder sb = new StringBuilder();
                    if (pts != null) {
                        for (Object pt : pts) {
                            if (pt instanceof Map<?, ?> pm) {
                                if (sb.length() > 0) sb.append("\n");
                                sb.append(fmtInstant(pm.get("recordedAt")))
                                  .append("  =>  ")
                                  .append(str(pm.get("occupancy")));
                            }
                        }
                    }
                    addTD(t, row++,
                        str(sm.get("shelterName")),
                        str(sm.get("capacity")),
                        sb.toString().isEmpty() ? "—" : sb.toString());
                }
            }
            doc.add(t);
        }
        doc.add(spacer(12));
    }

    private void writeResourceDistribution(Document doc, Map<?, ?> rd, int num) throws DocumentException {
        doc.add(sectionHeading(num + ". Resource Distribution"));

        List<?> byDistrict = asList(rd.get("byDistrict"));
        if (byDistrict != null && !byDistrict.isEmpty()) {
            doc.add(new Paragraph("By district & item", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{28f, 18f, 12f, 21f, 21f});
            addTH(t, "District", "Item", "Unit", "Allocated", "Distributed");
            int row = 0;
            for (Object r : byDistrict) {
                if (r instanceof Map<?, ?> rm) {
                    addTD(t, row++,
                        str(rm.get("districtName")),
                        str(rm.get("itemCode")),
                        str(rm.get("unit")),
                        str(rm.get("allocated")),
                        str(rm.get("distributed")));
                }
            }
            doc.add(t);
        }

        List<?> byOrgType = asList(rd.get("byOrganisationType"));
        if (byOrgType != null && !byOrgType.isEmpty()) {
            doc.add(spacer(6));
            doc.add(new Paragraph("By organisation type", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{60f, 40f});
            addTH(t, "Organisation Type", "Distributed");
            int row = 0;
            for (Object r : byOrgType) {
                if (r instanceof Map<?, ?> rm) {
                    addTD(t, row++, str(rm.get("type")), str(rm.get("distributed")));
                }
            }
            doc.add(t);
        }

        List<?> byItem = asList(rd.get("byItem"));
        if (byItem != null && !byItem.isEmpty()) {
            doc.add(spacer(6));
            doc.add(new Paragraph("By item (totals)", SUBHEAD_FONT));
            doc.add(spacer(3));
            PdfPTable t = makeTable(new float[]{45f, 20f, 35f});
            addTH(t, "Item", "Unit", "Distributed");
            int row = 0;
            for (Object r : byItem) {
                if (r instanceof Map<?, ?> rm) {
                    addTD(t, row++, str(rm.get("itemCode")), str(rm.get("unit")), str(rm.get("distributed")));
                }
            }
            doc.add(t);
        }
        doc.add(spacer(12));
    }

    private void writeUnavailable(Document doc, List<Map<String, String>> unavail) throws DocumentException {
        if (unavail == null || unavail.isEmpty()) return;
        doc.add(spacer(4));
        for (Map<String, String> u : unavail) {
            String title = SectionKey.fromAnyName(u.get("key")).map(PdfReportExporter::title).orElse(str(u.get("key")));
            doc.add(sectionHeading(title));
            doc.add(new Paragraph(AnalyticsRules.DATA_UNAVAILABLE + " — " + u.getOrDefault("reason", "No reason given."), SMALL_FONT));
            doc.add(spacer(8));
        }
    }

    private static String title(SectionKey key) {
        return switch (key) {
            case ALERT_TIMELINE -> "Alert Timeline";
            case CITIZENS_REACHED -> "Citizens Reached";
            case SHELTER_OCCUPANCY -> "Shelter Occupancy";
            case RESOURCE_DISTRIBUTION -> "Resource Distribution";
        };
    }

    // ── Table helpers ──────────────────────────────────────────────────────

    private PdfPTable makeTable(float[] widths) throws DocumentException {
        PdfPTable t = new PdfPTable(widths.length);
        t.setWidthPercentage(100f);
        t.setWidths(widths);
        t.setSpacingBefore(2f);
        t.setSpacingAfter(2f);
        t.setHeaderRows(1);
        return t;
    }

    private void addTH(PdfPTable t, String... cols) {
        for (String col : cols) {
            PdfPCell cell = new PdfPCell(new Phrase(col, TH_FONT));
            cell.setBackgroundColor(HEADER_BG);
            cell.setPadding(5f);
            cell.setBorderColor(HEADER_BG);
            t.addCell(cell);
        }
    }

    private void addTD(PdfPTable t, int row, String... values) {
        Color bg = row % 2 == 0 ? ROW_EVEN_BG : ROW_ODD_BG;
        for (String v : values) {
            PdfPCell cell = new PdfPCell(new Phrase(v == null ? "—" : v, SMALL_FONT));
            cell.setBackgroundColor(bg);
            cell.setPadding(4f);
            cell.setBorderColor(BORDER_COLOR);
            t.addCell(cell);
        }
    }

    // ── Paragraph helpers ──────────────────────────────────────────────────

    private Paragraph sectionHeading(String text) {
        Paragraph p = new Paragraph(text, HEADING_FONT);
        p.setSpacingBefore(8f);
        p.setSpacingAfter(4f);
        return p;
    }

    private Paragraph bodyLine(String text) { return new Paragraph(text, BODY_FONT); }

    private Paragraph spacer(float height) {
        Paragraph p = new Paragraph(" ");
        p.setLeading(height);
        return p;
    }

    private void addKv(Document doc, String label, Object value) throws DocumentException {
        if (value != null) {
            Paragraph p = new Paragraph();
            p.add(new Chunk(label + ":  ", SUBHEAD_FONT));
            p.add(new Chunk(String.valueOf(value), BODY_FONT));
            doc.add(p);
        }
    }

    // ── Type coercion helpers ──────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private List<?> asList(Object o) { return o instanceof List<?> l ? l : null; }

    private String str(Object o) { return o == null ? "—" : String.valueOf(o); }

    private long toLong(Object o) {
        if (o == null) return 0L;
        if (o instanceof Number n) return n.longValue();
        try { return Long.parseLong(String.valueOf(o)); } catch (Exception e) { return 0L; }
    }

    private double toDouble(Object o) {
        if (o == null) return 0.0;
        if (o instanceof Number n) return n.doubleValue();
        try { return Double.parseDouble(String.valueOf(o)); } catch (Exception e) { return 0.0; }
    }

    private String fmtInstant(Object o) {
        if (o == null) return "—";
        try {
            if (o instanceof Number n) {
                double val = n.doubleValue();
                long epochMillis = val > 1_000_000_000_000L ? (long) val : (long) (val * 1000);
                return DT_FMT.format(Instant.ofEpochMilli(epochMillis));
            }
            String s = String.valueOf(o);
            if (s.matches("\\d+\\.?\\d*")) {
                double val = Double.parseDouble(s);
                long epochMillis = val > 1_000_000_000_000L ? (long) val : (long) (val * 1000);
                return DT_FMT.format(Instant.ofEpochMilli(epochMillis));
            }
            return DT_FMT.format(Instant.parse(s));
        } catch (Exception e) {
            return String.valueOf(o);
        }
    }
}
