import { CHANNEL_LABEL, ORGANISATION_TYPE_LABEL } from '@/constants/labels'
import type { DisasterReport, OrganisationType } from '@/types'
import { formatDateTime } from '@/utils/format'
import { districtName } from './db'

function csvCell(value: string | number): string {
  const s = String(value)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

function rowsFor(report: DisasterReport): (string | number)[][] {
  const rows: (string | number)[][] = [
    ['Disaster response report'],
    ['Event', report.eventName],
    ['Generated', formatDateTime(report.generatedAt)],
    ['Generated by', report.generatedBy],
    [],
  ]
  const t = report.alertTimeline
  rows.push(['1. Alert timeline'])
  if (t) {
    rows.push(['Level', 'Status', 'Title', 'Issued', 'Districts'])
    t.entries.forEach((e) =>
      rows.push([e.level, e.status, e.title, formatDateTime(e.issuedAt), e.districtIds.map(districtName).join('; ')]),
    )
  } else rows.push(['Data unavailable'])
  rows.push([])

  const c = report.citizensReached
  rows.push(['2. Citizens reached'])
  if (c) {
    rows.push(['Targeted', c.targeted], ['Reached', c.reached], ['Delivery rate', `${Math.round(c.deliveryRate * 100)}%`])
    rows.push(['Channel', 'Delivered', 'Failed'])
    ;(Object.keys(c.byChannel) as (keyof typeof c.byChannel)[]).forEach((k) =>
      rows.push([CHANNEL_LABEL[k], c.byChannel[k].delivered, c.byChannel[k].failed]),
    )
    rows.push(['District', 'Targeted', 'Reached'])
    c.byDistrict.forEach((d) => rows.push([districtName(d.districtId), d.targeted, d.reached]))
  } else rows.push(['Data unavailable'])
  rows.push([])

  const s = report.shelterOccupancy
  rows.push(['3. Shelter occupancy'])
  if (s) {
    rows.push(['Shelter', 'Peak', 'Capacity', 'When'])
    s.peaks.forEach((p) => rows.push([p.name, p.peak, p.capacity, formatDateTime(p.at)]))
  } else rows.push(['Data unavailable'])
  rows.push([])

  const r = report.resourceDistribution
  rows.push(['4. Resource distribution'])
  if (r) {
    rows.push(['District and item', 'Allocated', 'Distributed'])
    r.byDistrictItem.forEach((d) => rows.push([d.label, d.allocated, d.distributed]))
    rows.push(['Organisation type', 'Distributed'])
    r.byOrganisationType.forEach((o) =>
      rows.push([ORGANISATION_TYPE_LABEL[o.type as OrganisationType] ?? o.type, o.distributed]),
    )
  } else rows.push(['Data unavailable'])
  return rows
}

export function buildCsv(report: DisasterReport): Blob {
  const text = rowsFor(report)
    .map((r) => r.map(csvCell).join(','))
    .join('\r\n')
  return new Blob(['﻿' + text], { type: 'text/csv;charset=utf-8' })
}

function pdfEscape(text: string): string {
  return text
    .replace(/[^\x20-\x7E]/g, '-')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

/** Minimal valid multi-page PDF (Helvetica text only), built without a library. */
export function buildPdf(report: DisasterReport): Blob {
  const lines = rowsFor(report).map((r) => r.join('   '))
  const perPage = 48
  const pages: string[][] = []
  for (let i = 0; i < lines.length; i += perPage) pages.push(lines.slice(i, i + perPage))
  if (!pages.length) pages.push([''])

  const objects: string[] = []
  const pageIds = pages.map((_, i) => 4 + i * 2)
  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>'
  objects[2] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >>`
  objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'
  pages.forEach((pageLines, i) => {
    const content = ['BT', '/F1 10 Tf', '14 TL', '50 790 Td']
    pageLines.forEach((l) => content.push(`(${pdfEscape(l).slice(0, 110)}) Tj T*`))
    content.push('ET')
    const stream = content.join('\n')
    objects[4 + i * 2] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5 + i * 2} 0 R >>`
    objects[5 + i * 2] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
  })

  let out = '%PDF-1.4\n'
  const offsets: number[] = []
  for (let id = 1; id < objects.length; id++) {
    offsets[id] = out.length
    out += `${id} 0 obj\n${objects[id]}\nendobj\n`
  }
  const xref = out.length
  out += `xref\n0 ${objects.length}\n0000000000 65535 f \n`
  for (let id = 1; id < objects.length; id++) out += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`
  out += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return new Blob([out], { type: 'application/pdf' })
}
